<?php

use ZillEAli\MikrotikLaravel\Services\ExportManager;

// SSH export methods (exportFull, exportSection) require a live SSH connection
// and are covered by integration testing. This file tests the pure PHP methods:
// parseConfig() and diffConfigs().

// ─── parseConfig ──────────────────────────────────────────────

it('parseConfig returns empty array for blank input', function () {
    $manager = new ExportManager('192.168.88.1');

    expect($manager->parseConfig(''))->toBeEmpty();
});

it('parseConfig groups commands under section headers', function () {
    $raw = <<<'EXPORT'
# RouterOS export

/ip address
add address=192.168.88.1/24 interface=ether1
add address=10.0.0.1/24 interface=ether2

/ip route
add dst-address=0.0.0.0/0 gateway=192.168.1.1
EXPORT;

    $manager = new ExportManager('192.168.88.1');
    $parsed = $manager->parseConfig($raw);

    expect($parsed)->toHaveKey('/ip address')
        ->and($parsed)->toHaveKey('/ip route')
        ->and($parsed['/ip address'])->toHaveCount(2)
        ->and($parsed['/ip route'])->toHaveCount(1);
});

it('parseConfig skips comment lines', function () {
    $raw = "# generated by RouterOS\n/ip address\nadd address=10.0.0.1/24 interface=lo\n";

    $manager = new ExportManager('192.168.88.1');
    $parsed = $manager->parseConfig($raw);

    expect($parsed)->toHaveKey('/ip address')
        ->and($parsed['/ip address'][0])->toContain('10.0.0.1');
});

it('parseConfig handles multiple sections', function () {
    $raw = <<<'EXPORT'
/ppp secret
add name=user1 password=pass1 service=pppoe
add name=user2 password=pass2 service=pppoe

/ppp profile
add name=10mbps rate-limit=10M/10M
EXPORT;

    $manager = new ExportManager('192.168.88.1');
    $parsed = $manager->parseConfig($raw);

    expect($parsed)->toHaveKey('/ppp secret')
        ->and($parsed)->toHaveKey('/ppp profile')
        ->and($parsed['/ppp secret'])->toHaveCount(2)
        ->and($parsed['/ppp profile'])->toHaveCount(1);
});

// ─── diffConfigs ──────────────────────────────────────────────

it('diffConfigs returns no changes for identical configs', function () {
    $config = "/ip address\nadd address=10.0.0.1/24 interface=lo\n";

    $manager = new ExportManager('192.168.88.1');
    $diff = $manager->diffConfigs($config, $config);

    expect($diff['added'])->toBeEmpty()
        ->and($diff['removed'])->toBeEmpty()
        ->and($diff['sections_changed'])->toBeEmpty();
});

it('diffConfigs detects added lines', function () {
    $before = "/ip address\nadd address=10.0.0.1/24 interface=lo\n";
    $after  = "/ip address\nadd address=10.0.0.1/24 interface=lo\nadd address=10.0.0.2/24 interface=lo\n";

    $manager = new ExportManager('192.168.88.1');
    $diff = $manager->diffConfigs($before, $after);

    expect($diff['added'])->toHaveCount(1)
        ->and($diff['removed'])->toBeEmpty()
        ->and($diff['sections_changed'])->toContain('/ip address');
});

it('diffConfigs detects removed lines', function () {
    $before = "/ip address\nadd address=10.0.0.1/24 interface=lo\nadd address=10.0.0.2/24 interface=lo\n";
    $after  = "/ip address\nadd address=10.0.0.1/24 interface=lo\n";

    $manager = new ExportManager('192.168.88.1');
    $diff = $manager->diffConfigs($before, $after);

    expect($diff['removed'])->toHaveCount(1)
        ->and($diff['added'])->toBeEmpty();
});

it('diffConfigs detects changes across multiple sections', function () {
    $before = <<<'BEFORE'
/ip address
add address=192.168.1.1/24 interface=ether1

/ip route
add dst-address=0.0.0.0/0 gateway=192.168.1.1
BEFORE;

    $after = <<<'AFTER'
/ip address
add address=192.168.1.1/24 interface=ether1
add address=10.0.0.1/24 interface=ether2

/ip route
add dst-address=0.0.0.0/0 gateway=192.168.1.1
AFTER;

    $manager = new ExportManager('192.168.88.1');
    $diff = $manager->diffConfigs($before, $after);

    expect($diff['added'])->toHaveCount(1)
        ->and($diff['removed'])->toBeEmpty()
        ->and($diff['sections_changed'])->toContain('/ip address')
        ->and($diff['sections_changed'])->not->toContain('/ip route');
});

it('diffConfigs result has required keys', function () {
    $manager = new ExportManager('192.168.88.1');
    $diff = $manager->diffConfigs('', '');

    expect($diff)->toHaveKeys(['added', 'removed', 'sections_changed']);
});

it('diffConfigs detects entirely new section in after', function () {
    $before = "/ip address\nadd address=10.0.0.1/24 interface=lo\n";
    $after  = "/ip address\nadd address=10.0.0.1/24 interface=lo\n/ip route\nadd dst-address=0.0.0.0/0 gateway=10.0.0.254\n";

    $manager = new ExportManager('192.168.88.1');
    $diff = $manager->diffConfigs($before, $after);

    expect($diff['sections_changed'])->toContain('/ip route')
        ->and($diff['added'])->not->toBeEmpty();
});
